import argparse
import pandas as pd
import main
import config

def run_batch_goals(csv_path):
    # Load CSV file
    df = pd.read_csv(csv_path)
    goals = df["Goal"].iloc[:50]
    
    count = 0
    # Call the main function for each target
    for goal in goals:
        print(f"Processing goal: {goal}")
        args.goal = goal
        # Call the main function every time
        count = count + main.main(args)

    print("success rate: {}".format(count / goals.size))

if __name__ == "__main__":
    # Use the "goal" to create command-line parameters
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--helper-model",
        default="deepseek-v3",
        choices=list(config.MODEL_PATH.keys()),
        help="Name of helper model."
    )
    parser.add_argument(
        "--target-model",
        default="mixtral-8x7b",
        choices=list(config.MODEL_PATH.keys()),
        help="Name of target model."
    )
    parser.add_argument(
        "--judge-model",
        default="gemma-3n",
        choices=list(config.MODEL_PATH.keys()),
        help="Name of judge model."
    )
    parser.add_argument(
        "--num-of-prompts",
        type=int,
        default=5,
        choices=range(1,20),
        help="Number of prompts generated by helper model."
    )
    parser.add_argument(
        "--goal",
        default="",
        help="Jailbreak goal."
    )
    parser.add_argument(
        "--local",
        action="store_true",
        default=False,
        help="run code on locally deployed model. (Not recommended)"
    )
    args = parser.parse_args()

    # Batch processing target
    run_batch_goals('./dataset/JBB-Behaviors/harmful-behaviors.csv')
