# liteLLM path of each model
MODEL_PATH = {
    "deepseek-v3": "deepseek-chat",
    "deepseek-r1": "deepseek-reasoner",
    "llama-4-maverick": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    "llama-4-scout": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "llama-3.3-70b": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    # "llama-3-8b": "meta-llama/Llama-3-8b-chat-hf",
    "llama-2-70b": "meta-llama/Llama-2-70b-chat-hf",#not usable now
    "llama-2-7b":"guojiaozhao24/meta-llama/Llama-2-7b-chat-hf-72c76bf4",
    "llama-3-8b":"meta-llama/Meta-Llama-3-8B-Instruct-Lite",
    "qwen-plus":"qwen-plus",
    "qwen-turbo": "qwen-turbo",
    "qwen-3-235b": "qwen3-235b-a22b",
    "kimi-k2": "kimi-k2-0711-preview",
    "gemma-3n": "google/gemma-3n-E4B-it",
    "mixtral-8x7b": "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "gemini-2.5-flash": "gemini-2.5-flash",
    "gemini-2.5-pro": "gemini-2.5-pro",
    "gpt-4.1": "gpt-4.1",
    "gpt-4.1-mini": "gpt-4.1-mini",
    "gpt-4o": "gpt-4o",
    "gpt-4":"gpt-4",
    "gpt-5-nano":"gpt-5-nano",
    "gpt-3.5-turbo":"gpt-3.5-turbo", 
    "gpt-4-turbo":"gpt-4-turbo",
    #"gpt-5-mini":"gpt-5-mini",
    #"gpt-5":"gpt-5",
    "claude-opus-4": "claude-opus-4-20250514",
    "claude-sonnet-4": "claude-sonnet-4-20250514",
    "claude-3-5-haiku": "claude-3-5-haiku-20241022",
    "vicuna":"lmsys/vicuna-13b-v1.5-16k"
}

# API key of each model
API_KEY = {
    "deepseek-v3": "CHATANYWHERE_API_KEY",
    "deepseek-r1": "CHATANYWHERE_API_KEY",
    "llama-4-maverick": "TOGETHER_API_KEY",
    "llama-4-scout": "TOGETHER_API_KEY",
    "llama-3.3-70b": "TOGETHER_API_KEY",
    "llama-3-8b": "TOGETHER_API_KEY",
    "llama-2-70b": "DEEPINFRA_API_KEY",
    "llama-2-7b":"TOGETHER_API_KEY",
    "qwen-plus": "DASHSCOPE_API_KEY",
    "qwen-turbo": "DASHSCOPE_API_KEY",
    "qwen-3-235b": "DASHSCOPE_API_KEY",
    "kimi-k2": "MOONSHOT_API_KEY",
    "gemma-3n": "TOGETHER_API_KEY",
    "mixtral-8x7b": "TOGETHER_API_KEY",
    "gemini-2.5-flash": "CHATANYWHERE_API_KEY",
    "gemini-2.5-pro": "CHATANYWHERE_API_KEY",
    "gpt-4.1": "CHATANYWHERE_API_KEY",
    "gpt-4.1-mini": "CHATANYWHERE_API_KEY",
    "gpt-4o": "METACHAT_API_KEY",
    "gpt-5-nano":"CHATANYWHERE_API_KEY",
    "gpt-3.5-turbo":"CHATANYWHERE_API_KEY",
    "gpt-4-turbo":"CHATANYWHERE_API_KEY",
    #"gpt-5-mini":"METACHAT_API_KEY", 
    #"gpt-5":"METACHAT_API_KEY",
    "gpt-4":"EVENAI_API_KEY",
    "claude-opus-4": "METACHAT_API_KEY",
    "claude-sonnet-4": "METACHAT_API_KEY",
    "claude-3-5-haiku": "CHATANYWHERE_API_KEY",
    "vicuna":"AIMLAPI_API_KEY"
}

BASE_URL = {
    "deepseek-v3": "https://api.chatanywhere.tech/v1",
    "deepseek-r1": "https://api.chatanywhere.tech/v1",
    "llama-4-maverick": "https://api.together.xyz/v1",
    "llama-4-scout": "https://api.together.xyz/v1",
    "llama-3.3-70b": "https://api.together.xyz/v1",
    "llama-3-8b": "https://api.together.xyz/v1",
    "llama-2-70b": "https://api.deepinfra.com/v1/openai",
    "llama-2-7b":"https://api.together.xyz/v1",
    "qwen-plus": "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "qwen-turbo": "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "qwen-3-235b": "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "kimi-k2": "https://api.moonshot.cn/v1",
    "gemma-3n": "https://api.together.xyz/v1",
    "mixtral-8x7b": "https://api.together.xyz/v1",
    "gemini-2.5-flash": "https://api.chatanywhere.tech/v1",
    "gemini-2.5-pro": "https://api.chatanywhere.tech/v1",
    "gpt-4.1": "https://api.chatanywhere.tech/v1",
    "gpt-4.1-mini": "https://api.chatanywhere.tech/v1",
    "gpt-4o": "https://llm-api.mmchat.xyz/v1",
    "gpt-5-nano":"https://api.chatanywhere.tech/v1",
    "gpt-3.5-turbo":"https://api.chatanywhere.tech/v1",
    "gpt-4-turbo":"https://api.chatanywhere.tech/v1",
    #"gpt-5-mini":"https://llm-api.mmchat.xyz/v1",
    #"gpt-5":"https://llm-api.mmchat.xyz/v1",
    "gpt-4": "https://api.evenai.top",
    "claude-opus-4": "https://llm-api.mmchat.xyz/v1",
    "claude-sonnet-4": "https://llm-api.mmchat.xyz/v1",
    "claude-3-5-haiku": "https://api.chatanywhere.tech/v1",
    "vicuna": "https://api.aimlapi.com/v1"
}